### ISSUE TITLE
Error while generating dynamic params

### ISSUE THREAD

**Issue by mohamed-Githu** [zdenham/next-static-utils#5]
I have a next.js project version : 13.3.2
We're trying to deploy the project on a CDN therefore we're trying to implement this package in this project.
I get an error while trying to run the CLI command.

![image](https://github.com/user-attachments/assets/4ee4c65c-a3a5-49fe-8540-e19fbeeebba6)

**Comment by zdenham** [comment]
This seems like an operating system level issue on windows. Curious if you are running low on disk space?

**Comment by mohamed-Githu** [comment]
I had discovered the problem. It was the low disk space.

**Comment by zdenham** [comment]
Sweet, will close for now
